
-- ============================================================
-- MALLBUDDY ANALYTICS EXTENSION - POSTGRESQL
-- ============================================================
-- Purpose:
--   Adds analytics capabilities to an existing MallBuddy
--   PostgreSQL database without dropping or replacing existing
--   MallBuddy tables.
--
-- IMPORTANT:
--   1. Keep your original schema backup unchanged.
--   2. Run this against a COPY/backup database first.
--   3. This script only ADDS analytics objects.
--   4. Synthetic data generated by this file is explicitly marked
--      as synthetic/development data.
--
-- Existing core tables expected:
--   malls, categories, stores, offers, facilities, events,
--   routes, users, admins, chat_sessions, chat_messages,
--   feedback, knowledge_docs, chatbot_settings, audit_logs
--
-- ============================================================

BEGIN;

-- ============================================================
-- 0. PostgreSQL helper
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. VISITOR SESSIONS
-- Tracks a MallBuddy visit, including anonymous/guest visitors.
-- ============================================================

CREATE TABLE IF NOT EXISTS visitor_sessions (
    id BIGSERIAL PRIMARY KEY,
    session_token VARCHAR(100) UNIQUE NOT NULL,
    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    device_type VARCHAR(30),
    is_guest BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_mall_time
    ON visitor_sessions(mall_id, started_at);

CREATE INDEX IF NOT EXISTS idx_visitor_sessions_user
    ON visitor_sessions(user_id);

-- ============================================================
-- 2. CENTRAL USER EVENT STREAM
-- Every important MallBuddy interaction becomes an event.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_events (
    id BIGSERIAL PRIMARY KEY,

    session_id BIGINT REFERENCES visitor_sessions(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,

    event_type VARCHAR(60) NOT NULL,

    store_id INTEGER REFERENCES stores(id) ON DELETE SET NULL,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    offer_id INTEGER REFERENCES offers(id) ON DELETE SET NULL,
    event_id INTEGER REFERENCES events(id) ON DELETE SET NULL,
    facility_id INTEGER REFERENCES facilities(id) ON DELETE SET NULL,

    search_query TEXT,

    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    is_synthetic BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_events_mall_time
    ON user_events(mall_id, created_at);

CREATE INDEX IF NOT EXISTS idx_user_events_type_time
    ON user_events(event_type, created_at);

CREATE INDEX IF NOT EXISTS idx_user_events_store_time
    ON user_events(store_id, created_at);

CREATE INDEX IF NOT EXISTS idx_user_events_category_time
    ON user_events(category_id, created_at);

CREATE INDEX IF NOT EXISTS idx_user_events_offer_time
    ON user_events(offer_id, created_at);

CREATE INDEX IF NOT EXISTS idx_user_events_session
    ON user_events(session_id);

CREATE INDEX IF NOT EXISTS idx_user_events_search
    ON user_events(search_query);

CREATE INDEX IF NOT EXISTS idx_user_events_metadata
    ON user_events USING GIN(metadata);

-- ============================================================
-- 3. DAILY MALL METRICS
-- Derived analytics cache for fast dashboard loading.
-- ============================================================

CREATE TABLE IF NOT EXISTS daily_mall_metrics (
    id BIGSERIAL PRIMARY KEY,
    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    metric_date DATE NOT NULL,

    total_sessions INTEGER NOT NULL DEFAULT 0,
    unique_visitors INTEGER NOT NULL DEFAULT 0,
    total_events INTEGER NOT NULL DEFAULT 0,

    store_searches INTEGER NOT NULL DEFAULT 0,
    store_views INTEGER NOT NULL DEFAULT 0,
    navigation_requests INTEGER NOT NULL DEFAULT 0,

    offer_views INTEGER NOT NULL DEFAULT 0,
    offer_clicks INTEGER NOT NULL DEFAULT 0,

    recommendation_views INTEGER NOT NULL DEFAULT 0,
    recommendation_clicks INTEGER NOT NULL DEFAULT 0,

    ai_queries INTEGER NOT NULL DEFAULT 0,
    feedback_count INTEGER NOT NULL DEFAULT 0,

    avg_session_seconds NUMERIC(12,2) DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(mall_id, metric_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_mall_metrics_date
    ON daily_mall_metrics(mall_id, metric_date);

-- ============================================================
-- 4. STORE PERFORMANCE
-- Derived store-level analytics.
-- ============================================================

CREATE TABLE IF NOT EXISTS store_performance (
    id BIGSERIAL PRIMARY KEY,

    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    store_id INTEGER NOT NULL REFERENCES stores(id) ON DELETE CASCADE,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    search_count INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    navigation_count INTEGER NOT NULL DEFAULT 0,

    offer_views INTEGER NOT NULL DEFAULT 0,
    offer_clicks INTEGER NOT NULL DEFAULT 0,

    recommendation_views INTEGER NOT NULL DEFAULT 0,
    recommendation_clicks INTEGER NOT NULL DEFAULT 0,

    favorite_count INTEGER NOT NULL DEFAULT 0,
    feedback_count INTEGER NOT NULL DEFAULT 0,

    engagement_score NUMERIC(8,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(mall_id, store_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_store_performance_mall_period
    ON store_performance(mall_id, period_start, period_end);

CREATE INDEX IF NOT EXISTS idx_store_performance_store
    ON store_performance(store_id);

-- ============================================================
-- 5. CATEGORY DEMAND
-- Used for demand-vs-supply intelligence.
-- ============================================================

CREATE TABLE IF NOT EXISTS category_demand (
    id BIGSERIAL PRIMARY KEY,

    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    search_count INTEGER NOT NULL DEFAULT 0,
    unique_sessions INTEGER NOT NULL DEFAULT 0,
    store_views INTEGER NOT NULL DEFAULT 0,
    navigation_count INTEGER NOT NULL DEFAULT 0,
    offer_interactions INTEGER NOT NULL DEFAULT 0,

    active_store_count INTEGER NOT NULL DEFAULT 0,

    previous_period_search_count INTEGER NOT NULL DEFAULT 0,
    growth_rate NUMERIC(8,2) NOT NULL DEFAULT 0,

    demand_score NUMERIC(8,2) NOT NULL DEFAULT 0,
    supply_gap_score NUMERIC(8,2) NOT NULL DEFAULT 0,

    demand_level VARCHAR(30) NOT NULL DEFAULT 'normal',

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(mall_id, category_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_category_demand_mall_period
    ON category_demand(mall_id, period_start, period_end);

CREATE INDEX IF NOT EXISTS idx_category_demand_score
    ON category_demand(demand_score DESC);

-- ============================================================
-- 6. OFFER PERFORMANCE
-- ============================================================

CREATE TABLE IF NOT EXISTS offer_performance (
    id BIGSERIAL PRIMARY KEY,

    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    store_id INTEGER NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    offer_id INTEGER NOT NULL REFERENCES offers(id) ON DELETE CASCADE,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    impressions INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    saves INTEGER NOT NULL DEFAULT 0,
    redemptions INTEGER NOT NULL DEFAULT 0,

    ctr NUMERIC(8,2) NOT NULL DEFAULT 0,
    conversion_rate NUMERIC(8,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(offer_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_offer_performance_mall_period
    ON offer_performance(mall_id, period_start, period_end);

CREATE INDEX IF NOT EXISTS idx_offer_performance_offer
    ON offer_performance(offer_id);

-- ============================================================
-- 7. CUSTOMER SEGMENTS
-- Stores ML-generated segment assignments.
-- The actual ML training remains in Python.
-- ============================================================

CREATE TABLE IF NOT EXISTS customer_segments (
    id BIGSERIAL PRIMARY KEY,

    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT REFERENCES visitor_sessions(id) ON DELETE SET NULL,

    segment_number INTEGER NOT NULL,
    segment_name VARCHAR(100),

    model_version VARCHAR(50) NOT NULL,
    feature_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(mall_id, user_id, model_version)
);

CREATE INDEX IF NOT EXISTS idx_customer_segments_mall
    ON customer_segments(mall_id);

CREATE INDEX IF NOT EXISTS idx_customer_segments_segment
    ON customer_segments(mall_id, segment_number);

-- ============================================================
-- 8. AI BUSINESS INSIGHTS
-- Stores evidence-backed recommendations shown to admins.
-- ============================================================

CREATE TABLE IF NOT EXISTS ai_business_insights (
    id BIGSERIAL PRIMARY KEY,

    mall_id INTEGER NOT NULL REFERENCES malls(id) ON DELETE CASCADE,

    insight_type VARCHAR(60) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    recommendation TEXT,

    severity VARCHAR(30) DEFAULT 'info',

    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,

    model_name VARCHAR(100),
    model_version VARCHAR(50),

    period_start DATE,
    period_end DATE,

    status VARCHAR(30) NOT NULL DEFAULT 'active',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ai_insights_mall_status
    ON ai_business_insights(mall_id, status);

CREATE INDEX IF NOT EXISTS idx_ai_insights_created
    ON ai_business_insights(created_at DESC);

-- ============================================================
-- 9. ANALYTICS VIEWS
-- These calculate useful metrics directly from user_events.
-- ============================================================

CREATE OR REPLACE VIEW vw_category_search_demand AS
SELECT
    ue.mall_id,
    ue.category_id,
    c.name AS category_name,
    COUNT(*) AS search_count,
    COUNT(DISTINCT ue.session_id) AS unique_sessions,
    COUNT(DISTINCT ue.user_id) FILTER (WHERE ue.user_id IS NOT NULL)
        AS unique_logged_users,
    MIN(ue.created_at) AS first_event,
    MAX(ue.created_at) AS last_event
FROM user_events ue
JOIN categories c ON c.id = ue.category_id
WHERE ue.event_type IN ('store_search', 'category_search')
GROUP BY ue.mall_id, ue.category_id, c.name;

CREATE OR REPLACE VIEW vw_store_engagement AS
SELECT
    s.id AS store_id,
    s.mall_id,
    s.name AS store_name,
    s.category_id,
    COUNT(*) FILTER (WHERE ue.event_type = 'store_search') AS searches,
    COUNT(*) FILTER (WHERE ue.event_type = 'store_view') AS views,
    COUNT(*) FILTER (WHERE ue.event_type = 'navigation_request') AS navigation_requests,
    COUNT(*) FILTER (WHERE ue.event_type = 'offer_view') AS offer_views,
    COUNT(*) FILTER (WHERE ue.event_type = 'offer_click') AS offer_clicks,
    COUNT(*) FILTER (WHERE ue.event_type = 'recommendation_view') AS recommendation_views,
    COUNT(*) FILTER (WHERE ue.event_type = 'recommendation_click') AS recommendation_clicks
FROM stores s
LEFT JOIN user_events ue ON ue.store_id = s.id
GROUP BY s.id, s.mall_id, s.name, s.category_id;

CREATE OR REPLACE VIEW vw_hourly_activity AS
SELECT
    mall_id,
    EXTRACT(HOUR FROM created_at)::INTEGER AS hour_of_day,
    COUNT(*) AS total_events,
    COUNT(DISTINCT session_id) AS sessions
FROM user_events
GROUP BY mall_id, EXTRACT(HOUR FROM created_at)::INTEGER;

CREATE OR REPLACE VIEW vw_event_type_summary AS
SELECT
    mall_id,
    event_type,
    COUNT(*) AS event_count,
    COUNT(DISTINCT session_id) AS unique_sessions,
    COUNT(DISTINCT user_id) FILTER (WHERE user_id IS NOT NULL)
        AS unique_users
FROM user_events
GROUP BY mall_id, event_type;

-- ============================================================
-- 10. FUNCTION: CALCULATE CATEGORY DEMAND
-- This is deterministic analytics, not an LLM decision.
-- ============================================================

CREATE OR REPLACE FUNCTION refresh_category_demand(
    p_mall_id INTEGER,
    p_start_date DATE,
    p_end_date DATE
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN

    INSERT INTO category_demand (
        mall_id,
        category_id,
        period_start,
        period_end,
        search_count,
        unique_sessions,
        store_views,
        navigation_count,
        offer_interactions,
        active_store_count,
        demand_score,
        supply_gap_score,
        demand_level
    )
    SELECT
        p_mall_id,
        c.id,
        p_start_date,
        p_end_date,

        COALESCE(COUNT(*) FILTER (
            WHERE ue.event_type IN ('store_search', 'category_search')
        ), 0),

        COALESCE(COUNT(DISTINCT ue.session_id), 0),

        COALESCE(COUNT(*) FILTER (
            WHERE ue.event_type = 'store_view'
        ), 0),

        COALESCE(COUNT(*) FILTER (
            WHERE ue.event_type = 'navigation_request'
        ), 0),

        COALESCE(COUNT(*) FILTER (
            WHERE ue.event_type IN ('offer_view', 'offer_click')
        ), 0),

        (
            SELECT COUNT(*)
            FROM stores s
            WHERE s.mall_id = p_mall_id
              AND s.category_id = c.id
              AND LOWER(COALESCE(s.status, 'open')) = 'open'
        ),

        LEAST(
            100,
            (
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type IN ('store_search', 'category_search')
                ), 0) * 0.35
                +
                COALESCE(COUNT(DISTINCT ue.session_id), 0) * 0.20
                +
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type = 'navigation_request'
                ), 0) * 0.25
                +
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type IN ('offer_view', 'offer_click')
                ), 0) * 0.20
            ) / GREATEST(
                1,
                COUNT(*) FILTER (
                    WHERE ue.event_type IN ('store_search', 'category_search')
                )
            ) * 100
        ),

        CASE
            WHEN (
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type IN ('store_search', 'category_search')
                ), 0)
                /
                GREATEST(
                    1,
                    (
                        SELECT COUNT(*)
                        FROM stores s2
                        WHERE s2.mall_id = p_mall_id
                          AND s2.category_id = c.id
                          AND LOWER(COALESCE(s2.status, 'open')) = 'open'
                    )
                )
            ) >= 500 THEN 100
            WHEN (
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type IN ('store_search', 'category_search')
                ), 0)
                /
                GREATEST(
                    1,
                    (
                        SELECT COUNT(*)
                        FROM stores s2
                        WHERE s2.mall_id = p_mall_id
                          AND s2.category_id = c.id
                          AND LOWER(COALESCE(s2.status, 'open')) = 'open'
                    )
                )
            ) >= 250 THEN 70
            WHEN (
                COALESCE(COUNT(*) FILTER (
                    WHERE ue.event_type IN ('store_search', 'category_search')
                ), 0)
                /
                GREATEST(
                    1,
                    (
                        SELECT COUNT(*)
                        FROM stores s2
                        WHERE s2.mall_id = p_mall_id
                          AND s2.category_id = c.id
                          AND LOWER(COALESCE(s2.status, 'open')) = 'open'
                    )
                )
            ) >= 100 THEN 40
            ELSE 10
        END,

        CASE
            WHEN COALESCE(COUNT(*) FILTER (
                WHERE ue.event_type IN ('store_search', 'category_search')
            ), 0) >= 1000 THEN 'high'
            WHEN COALESCE(COUNT(*) FILTER (
                WHERE ue.event_type IN ('store_search', 'category_search')
            ), 0) >= 500 THEN 'growing'
            WHEN COALESCE(COUNT(*) FILTER (
                WHERE ue.event_type IN ('store_search', 'category_search')
            ), 0) >= 100 THEN 'normal'
            ELSE 'low'
        END

    FROM categories c
    LEFT JOIN user_events ue
        ON ue.category_id = c.id
       AND ue.mall_id = p_mall_id
       AND ue.created_at >= p_start_date
       AND ue.created_at < (p_end_date + INTERVAL '1 day')

    GROUP BY c.id

    ON CONFLICT (mall_id, category_id, period_start, period_end)
    DO UPDATE SET
        search_count = EXCLUDED.search_count,
        unique_sessions = EXCLUDED.unique_sessions,
        store_views = EXCLUDED.store_views,
        navigation_count = EXCLUDED.navigation_count,
        offer_interactions = EXCLUDED.offer_interactions,
        active_store_count = EXCLUDED.active_store_count,
        demand_score = EXCLUDED.demand_score,
        supply_gap_score = EXCLUDED.supply_gap_score,
        demand_level = EXCLUDED.demand_level,
        generated_at = NOW();

END;
$$;

-- ============================================================
-- 11. FUNCTION: REFRESH DAILY MALL METRICS
-- ============================================================

CREATE OR REPLACE FUNCTION refresh_daily_mall_metrics(
    p_mall_id INTEGER,
    p_metric_date DATE
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN

    INSERT INTO daily_mall_metrics (
        mall_id,
        metric_date,
        total_sessions,
        unique_visitors,
        total_events,
        store_searches,
        store_views,
        navigation_requests,
        offer_views,
        offer_clicks,
        recommendation_views,
        recommendation_clicks,
        ai_queries,
        feedback_count,
        avg_session_seconds
    )
    SELECT
        p_mall_id,
        p_metric_date,

        (
            SELECT COUNT(*)
            FROM visitor_sessions vs
            WHERE vs.mall_id = p_mall_id
              AND vs.started_at >= p_metric_date
              AND vs.started_at < (p_metric_date + INTERVAL '1 day')
        ),

        (
            SELECT COUNT(DISTINCT COALESCE(vs.user_id::TEXT, vs.session_token))
            FROM visitor_sessions vs
            WHERE vs.mall_id = p_mall_id
              AND vs.started_at >= p_metric_date
              AND vs.started_at < (p_metric_date + INTERVAL '1 day')
        ),

        COUNT(*),

        COUNT(*) FILTER (WHERE ue.event_type IN ('store_search', 'category_search')),
        COUNT(*) FILTER (WHERE ue.event_type = 'store_view'),
        COUNT(*) FILTER (WHERE ue.event_type = 'navigation_request'),
        COUNT(*) FILTER (WHERE ue.event_type = 'offer_view'),
        COUNT(*) FILTER (WHERE ue.event_type = 'offer_click'),
        COUNT(*) FILTER (WHERE ue.event_type = 'recommendation_view'),
        COUNT(*) FILTER (WHERE ue.event_type = 'recommendation_click'),
        COUNT(*) FILTER (WHERE ue.event_type = 'ai_query'),
        COUNT(*) FILTER (WHERE ue.event_type = 'feedback_submitted'),

        COALESCE(
            (
                SELECT AVG(
                    EXTRACT(EPOCH FROM (vs.ended_at - vs.started_at))
                )
                FROM visitor_sessions vs
                WHERE vs.mall_id = p_mall_id
                  AND vs.started_at >= p_metric_date
                  AND vs.started_at < (p_metric_date + INTERVAL '1 day')
                  AND vs.ended_at IS NOT NULL
            ),
            0
        )

    FROM user_events ue
    WHERE ue.mall_id = p_mall_id
      AND ue.created_at >= p_metric_date
      AND ue.created_at < (p_metric_date + INTERVAL '1 day')

    ON CONFLICT (mall_id, metric_date)
    DO UPDATE SET
        total_sessions = EXCLUDED.total_sessions,
        unique_visitors = EXCLUDED.unique_visitors,
        total_events = EXCLUDED.total_events,
        store_searches = EXCLUDED.store_searches,
        store_views = EXCLUDED.store_views,
        navigation_requests = EXCLUDED.navigation_requests,
        offer_views = EXCLUDED.offer_views,
        offer_clicks = EXCLUDED.offer_clicks,
        recommendation_views = EXCLUDED.recommendation_views,
        recommendation_clicks = EXCLUDED.recommendation_clicks,
        ai_queries = EXCLUDED.ai_queries,
        feedback_count = EXCLUDED.feedback_count,
        avg_session_seconds = EXCLUDED.avg_session_seconds,
        updated_at = NOW();

END;
$$;

-- ============================================================
-- 12. SYNTHETIC DEVELOPMENT DATA GENERATOR
-- IMPORTANT:
--   This does NOT pretend to be real mall data.
--   Run manually when you want development/test data.
--
-- Example:
--   SELECT generate_mallbuddy_synthetic_data(1, 10000, 30);
-- ============================================================

CREATE OR REPLACE FUNCTION generate_mallbuddy_synthetic_data(
    p_mall_id INTEGER,
    p_event_count INTEGER DEFAULT 10000,
    p_days INTEGER DEFAULT 30
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    i INTEGER;
    v_session_id BIGINT;
    v_session_token VARCHAR(100);
    v_user_id INTEGER;
    v_store_id INTEGER;
    v_category_id INTEGER;
    v_offer_id INTEGER;
    v_event_type VARCHAR(60);
    v_created_at TIMESTAMPTZ;
    v_query TEXT;
    v_inserted INTEGER := 0;
BEGIN

    IF NOT EXISTS (
        SELECT 1 FROM malls WHERE id = p_mall_id
    ) THEN
        RAISE EXCEPTION 'Mall ID % does not exist', p_mall_id;
    END IF;

    FOR i IN 1..p_event_count LOOP

        v_session_token :=
            'SYN-' ||
            TO_CHAR(NOW(), 'YYYYMMDDHH24MISS') ||
            '-' ||
            LPAD(i::TEXT, 8, '0');

        v_user_id := NULL;

        IF random() < 0.35 THEN
            SELECT id
            INTO v_user_id
            FROM users
            WHERE is_active = TRUE
            ORDER BY random()
            LIMIT 1;
        END IF;

        INSERT INTO visitor_sessions (
            session_token,
            mall_id,
            user_id,
            started_at,
            ended_at,
            device_type,
            is_guest
        )
        VALUES (
            v_session_token,
            p_mall_id,
            v_user_id,
            NOW() - (random() * p_days * INTERVAL '1 day'),
            NULL,
            CASE
                WHEN random() < 0.65 THEN 'mobile'
                WHEN random() < 0.90 THEN 'desktop'
                ELSE 'tablet'
            END,
            v_user_id IS NULL
        )
        RETURNING id INTO v_session_id;

        SELECT id
        INTO v_store_id
        FROM stores
        WHERE mall_id = p_mall_id
        ORDER BY random()
        LIMIT 1;

        IF v_store_id IS NOT NULL THEN
            SELECT category_id
            INTO v_category_id
            FROM stores
            WHERE id = v_store_id;
        END IF;

        SELECT id
        INTO v_offer_id
        FROM offers o
        JOIN stores s ON s.id = o.store_id
        WHERE s.mall_id = p_mall_id
        ORDER BY random()
        LIMIT 1;

        -- Weighted behavior:
        -- searches and store views intentionally occur more often
        -- than rare actions such as favorites/redemptions.
        v_event_type :=
            CASE
                WHEN random() < 0.18 THEN 'store_search'
                WHEN random() < 0.33 THEN 'store_view'
                WHEN random() < 0.46 THEN 'navigation_request'
                WHEN random() < 0.57 THEN 'offer_view'
                WHEN random() < 0.64 THEN 'offer_click'
                WHEN random() < 0.71 THEN 'ai_query'
                WHEN random() < 0.78 THEN 'recommendation_view'
                WHEN random() < 0.84 THEN 'recommendation_click'
                WHEN random() < 0.90 THEN 'category_search'
                WHEN random() < 0.94 THEN 'favorite_added'
                WHEN random() < 0.97 THEN 'event_view'
                ELSE 'feedback_submitted'
            END;

        v_created_at :=
            NOW() - (random() * p_days * INTERVAL '1 day');

        v_query :=
            CASE
                WHEN v_event_type IN ('store_search', 'category_search') THEN
                    CASE
                        WHEN random() < 0.22 THEN 'cafe'
                        WHEN random() < 0.40 THEN 'restaurant'
                        WHEN random() < 0.52 THEN 'coffee'
                        WHEN random() < 0.64 THEN 'fashion'
                        WHEN random() < 0.74 THEN 'shoes'
                        WHEN random() < 0.82 THEN 'electronics'
                        WHEN random() < 0.89 THEN 'beauty'
                        WHEN random() < 0.95 THEN 'cinema'
                        ELSE 'kids'
                    END
                WHEN v_event_type = 'ai_query' THEN
                    CASE
                        WHEN random() < 0.25 THEN 'Where can I get coffee?'
                        WHEN random() < 0.45 THEN 'Show me fashion stores'
                        WHEN random() < 0.62 THEN 'Where can I eat?'
                        WHEN random() < 0.76 THEN 'Where is the cinema?'
                        WHEN random() < 0.88 THEN 'Find sports stores'
                        ELSE 'What offers are available today?'
                    END
                ELSE NULL
            END;

        INSERT INTO user_events (
            session_id,
            user_id,
            mall_id,
            event_type,
            store_id,
            category_id,
            offer_id,
            search_query,
            metadata,
            is_synthetic,
            created_at
        )
        VALUES (
            v_session_id,
            v_user_id,
            p_mall_id,
            v_event_type,
            CASE
                WHEN v_event_type IN (
                    'store_view',
                    'navigation_request',
                    'offer_view',
                    'offer_click',
                    'recommendation_view',
                    'recommendation_click',
                    'favorite_added'
                )
                THEN v_store_id
                ELSE NULL
            END,
            CASE
                WHEN v_event_type IN (
                    'store_search',
                    'category_search',
                    'store_view',
                    'navigation_request'
                )
                THEN v_category_id
                ELSE NULL
            END,
            CASE
                WHEN v_event_type IN ('offer_view', 'offer_click')
                THEN v_offer_id
                ELSE NULL
            END,
            v_query,
            jsonb_build_object(
                'source', 'synthetic_development_data',
                'generator_version', '1.0',
                'device_type',
                    CASE
                        WHEN random() < 0.65 THEN 'mobile'
                        WHEN random() < 0.90 THEN 'desktop'
                        ELSE 'tablet'
                    END
            ),
            TRUE,
            v_created_at
        );

        v_inserted := v_inserted + 1;
    END LOOP;

    RETURN v_inserted;
END;
$$;

-- ============================================================
-- 13. SAMPLE DATASET GENERATION COMMAND
-- COMMENTED OUT ON PURPOSE.
--
-- After verifying the schema, run:
--
-- SELECT generate_mallbuddy_synthetic_data(1, 100000, 60);
--
-- This creates 100,000 synthetic events for mall ID 1
-- across a 60-day time window.
-- ============================================================

-- SELECT generate_mallbuddy_synthetic_data(1, 100000, 60);

-- ============================================================
-- 14. EXAMPLE ANALYTICS QUERIES
-- ============================================================

-- Top searched categories:
--
-- SELECT *
-- FROM vw_category_search_demand
-- WHERE mall_id = 1
-- ORDER BY search_count DESC;

-- Most requested stores:
--
-- SELECT
--     store_name,
--     searches,
--     views,
--     navigation_requests
-- FROM vw_store_engagement
-- WHERE mall_id = 1
-- ORDER BY searches DESC
-- LIMIT 10;

-- Peak hours:
--
-- SELECT *
-- FROM vw_hourly_activity
-- WHERE mall_id = 1
-- ORDER BY sessions DESC;

-- Event distribution:
--
-- SELECT *
-- FROM vw_event_type_summary
-- WHERE mall_id = 1
-- ORDER BY event_count DESC;

-- Refresh category demand for a period:
--
-- SELECT refresh_category_demand(
--     1,
--     CURRENT_DATE - INTERVAL '30 days',
--     CURRENT_DATE
-- );

-- Refresh today's mall metrics:
--
-- SELECT refresh_daily_mall_metrics(
--     1,
--     CURRENT_DATE
-- );

COMMIT;

-- ============================================================
-- END OF MALLBUDDY ANALYTICS EXTENSION
-- ============================================================
